<?php
$this->title = 'Σχετικά';
$this->url = BASE_URL . 'about';
?>

<div class="inner-page">
  <div class="slider-item" style="background-image: url('images/panzano.png');">
    <div class="container">
      <div class="row slider-text align-items-center justify-content-center">
        <div class="col-lg-9 text-center col-sm-12 element-animate">
          <h1 class="display-4 my-4"><!--About Us--><?php echo $this->title; ?></h1>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="wrapper">
  <div class="section">
  	<div class="container">
  		<div class="row">
  			<div class="col-md-7">
  				<h2 class="mb-4" style="letter-spacing: 5px;font-weight: 400;color: #323e55;font-size: 2.3rem;">About Wine Virtue</h2>
  				<div class="text-justify">
  					<p>Γεννημένος εν Aθήναις, στο οινικά άδοξο 1984 και μεγαλωμένος στο εξωτικό Λουτράκι με καταγωγή από τον Νομό της Μαλαγουζιάς, αυτόν της Αιτωλοακαρνανίας, που δεν βγάζει πλέον Μαλαγουζιά… ..πώς τα φέρνει η άτιμη η ζωή..!</p>
						<p>Έτσι όπως τα γυρνάει από εδώ και τα φέρνει από εκεί, στα 30 μου ταξιδεύοντας στην Αιώνια Πόλη, την Ρώμη, μου εμβολιάστηκε το μικρόβιο της ασχολίας με το κρασί και τον κόσμο που το περιβάλλει, το αναπτύσσει και το επικοινωνεί.</p>
						<p>Ακολούθως, σειρά είχαν τα σεμινάρια οινικής απόλαυσης του Θοδωρή Λέλεκα όπου το μικρόβιο αναπτύχθηκε. Πέραν της γνώσης, το μεγαλύτερο κέρδος είναι οι φίλοι και οι γνωστοί πλέον #WineLoverseminarAlumni που γνωρίζει κανείς σε τέτοια σεμινάρια και μέρη. Μοιραία, ακολούθησαν εκδρομές και γευσιγνωσίες,  θεματικές βραδιές με γεμάτα τραπέζια, γέλια, χαρές και λύπες αλλά με το κρασί να τις συνοδεύει και να γίνεται αυτό το κάτι παραπάνω που κάνει τις στιγμές μοναδικές.</p>
						<p>Στο χάρτη χαράχτηκαν κι άλλα ταξίδια, όπως και περισσότερες γευσιγνωσίες. Μελετήθηκαν βιβλία και σε,τι μπορεί να φανταστεί κανείς σχετικά με το Κρασί.</p>
						<p>Μεγάλος σταθμός γνώσης η συμμετοχή μου στην εξαιρετική σχολή Οινοχόων της “Genius in Gastronomy” μεγεθύνοντας την γνώση και τον ζήλο για ακόμα περισσότερη κατάρτιση και οινικές ανακαλύψεις. Μέσα σε όλα αυτά, ήρθε και η συμμετοχή μου σε έναν από τους μεγαλύτερους και πιο αξιόπιστους διαγωνισμούς στον κόσμο, αυτόν του “International Wine and Spirits Competition” που λαμβάνει χώρα κάθε χρόνο στο Λονδίνο και στο οποίο έχω τον τιμητικό ρόλο του κριτή ελληνικών (κι όχι μόνο) οίνων, καθώς η Μεσόγειος έχει να χαρίσει πολλές οινικές συγκινήσεις κι αποκαλύψεις που δεν περιμένεις!!! Και τώρα, τι;</p>
						<p>Πλέον, θα ήθελα να σας προσκαλέσω να ασχοληθείτε κι εσείς με το κρασί, να το προσθέσετε στα κυριακάτικα τραπέζια, στις στιγμές χαλάρωσης, στις γιορτές και στις επετείους σας, και αν κολλήσετε και εσείς το όμορφο αυτό μικρόβιο τότε η σελίδα αυτή θα έχει πετύχει τον σκοπό της που δεν είναι άλλος από το να ανοίξει τον κόσμο του κρασιού σε ολοένα και περισσότερο κόσμο. Θα χαρώ πολύ να εισέλθετε στο μαγικό κόσμο του οίνου που υπόσχεται τη μέγιστη δυνατή απογείωση των αισθήσεών σας, σε ένα ταξίδι που θα μας βρει συνοδοιπόρους, εξερευνητές και ιχνηλάτες της πιο ποιοτικής εμπειρίας..!</p>
						<p>Καλώς ήλθατε, λοιπόν...</p>
					</div>
  			</div>
  			<div class="col-md-5">
  				<img src="images/the_hand.jpg" class="img-fluid" style="margin-top: 80px;">

  				<div class="row mt-5">
  					<div class="col-6">
  						<a href="https://iwsc.net/" target="_blank"><img src="images/IWSC-logo.png" class="img-fluid"></a>
  					</div>
  					<div class="col-6">
  						<a href="http://www.geniusingastronomy.gr/el/" target="_blank"><img src="images/genius.png" class="img-fluid"></a>
  					</div>
  						<!--<div class="col-4">
  							<a href="https://www.wsetglobal.com/"><img src="images/wset logo isolated.webp" class="img-fluid"></a>
  						</div>-->
  				</div>
  				<div class="row mt-2">
  					<div class="col-6">
  						<a href="http://greeksom.com/" target="_blank"><img src="images/Greek-Somms.png" class="img-fluid"></a>
  					</div>
  					<div class="col-6 my-auto">
  						<img src="images/winelovers-Seminar.jpg" class="img-fluid">
  					</div>
  				</div>
        </div>
  		</div>
  	</div> <!-- /.container -->
  </div> <!-- /.section -->
</div> <!-- /.wrapper -->