<?php
$this->title = 'Error';
?>

<div class="inner-page">
  <div class="slider-item" style="background-image: url('/images/panzano.png');">
    <div class="container">
      <div class="row slider-text align-items-center justify-content-center">
        	<div class="col-lg-9 text-center col-sm-12 element-animate">
          	<h1 class="display-4 my-4"><?php echo $this->title; ?></h1>
        	</div>
      </div>
    </div>
  </div>
</div>

<div class="wrapper">
  <div class="section">
    	<div class="container">
			<h1>Error Page</h1>
			<h2><?php print ($params["exception"]->getCode() . " - " . $params["exception"]->getMessage()); ?></h2>
		</div>
	</div>
</div>