<?php
  	$this->title = 'Manage Posts';
  	$posts = $params['model']; // Get all posts from DB
?>

<div id="content-wrapper">
	<div class="container-fluid">
		<!-- Breadcrumbs-->
        <ol class="breadcrumb">
          	<li class="breadcrumb-item">
            	<a href="dashboard">Dashboard</a>
          	</li>
          	<li class="breadcrumb-item active">Manage Posts</li>
        </ol>
        <!-- Articles DataTables -->
        <div class="card mb-3">
          	<div class="card-header">
            	<i class="fas fa-table"></i> Database Posts Table
            </div>
          	
          	<div class="card-body">
          		<!-- Display notification message -->
	          	<?php include ROOT_PATH . 'app/includes/messages.php'; ?>
				
				<!-- Display records from DB-->
            	<div class="table-responsive">
            		<?php if (empty($posts)): ?>
						<h1 class="text-center">No articles in the database.</h1>
					<?php else: ?>
						<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
							<thead>
								<th>#</th>
								<th>Author</th>
								<th>Title</th>
								<!-- Only Admin can publish/unpublish post -->
								<?php if (app\src\Application::$app->user->role == "Admin"): ?>
									<th><small>Publish</small></th>
								<?php endif ?>
								<th><small>Edit</small></th>
								<th><small>Delete</small></th>
							</thead>
							<tbody>
								<?php foreach ($posts as $key => $post): ?>
									<tr>
										<td><?php echo $key + 1; ?></td>
										<td><?php echo $post->author; ?></td>
										<td>
											<a target="_blank" href="<?php echo BASE_URL . 'article/' . $post->slug ?>">
												<?php echo $post->title; ?>
											</a>
										</td>
										
										<!-- Only Admin can publish/unpublish post -->
										<?php if (app\src\Application::$app->user->role == "Admin" ): ?>
										<td class="text-center">
											<?php if ($post->published == true): ?>
												<a class="btn btn-outline-dark border-0 rounded-circle" 
													href="post/unpublish/<?php echo $post->id ?>">
													<i class="fas fa-check"></i>
												</a>
											<?php else: ?>
												<a class="btn btn-outline-dark border-0 rounded-circle" 
													href="post/publish/<?php echo $post->id ?>">
													<i class="fas fa-times"></i>
												</a>
											<?php endif ?>
										</td>
										<?php endif ?>
										<td class="text-center">
											<a class="btn btn-outline-info btn-sm"
												href="post/edit/<?php echo $post->id ?>">
												<i class="far fa-edit"></i> Edit
											</a>
										</td>
										<td class="text-center">
											<a class="btn btn-outline-danger btn-sm delete_post"
												href="#" data-toggle="modal" data-target="#deleteModal" data-id="<?php echo $post->id ?>">
												<i class="far fa-trash-alt"></i> Delete
											</a>
										</td>
									</tr>
								<?php endforeach ?>
							</tbody>
						</table>
					<?php endif ?>
				</div>	<!-- // Display records from DB -->
          	</div>
          	<div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
        </div>			
	</div>	<!-- /.container-fluid -->	
</div>	<!-- /.content-wrapper -->