<?php
	$this->title = 'Αναζήτηση';
	$this->url = BASE_URL . 'search';
	$posts = $params['posts'];
	$wines = $params['wines'];
?>

<div class="inner-page">
    <div class="slider-item" style="background-image: url('images/panzano.png');">
      	<div class="container">
          	<div class="row slider-text align-items-center justify-content-center">
            	<div class="col-lg-9 text-center col-sm-12 element-animate">
              		<h1 class="display-4"><!--Search--><?php echo $this->title; ?></h1>
            	</div>
          	</div>
      	</div>
    </div>
</div>

<div class="wrapper">
	<div class="container">
		<div class="section">
			<form action="search" id="searchForm" method="post" class="search-form">
				<div class="input-group mb-3">
		  			<input type="text" class="form-control <?php echo $params['model']->hasError('search') ? 'is-invalid' : '' ?>" name="search" placeholder="Αναζήτηση..." aria-label="search-input" value="<?php echo htmlspecialchars($params['model']->search); ?>" required>
		  			<div class="input-group-append">
		    			<button class="btn btn-outline-primary" type="submit">Search</button>
		  			</div>
					<div class="invalid-feedback">
                        <?php echo $params['model']->getFirstError('search') ?>
                    </div>
				</div>
			</form>

			<ul class="nav nav-tabs" id="searchTab" role="tablist">
				<li class="nav-item">
				   <a class="nav-link active" href="#articles" data-toggle="tab" role="tab" aria-controls="articles" aria-selected="true">Άρθρα</a>
				</li>
				<li class="nav-item">
				   <a class="nav-link" href="#reviews" data-toggle="tab" role="tab" aria-controls="wine-revies" aria-selected="false">Κριτικές</a>
				</li>
			</ul>

			<div class="tab-content" id="myTabContent">
				<div class="tab-pane fade show active" id="articles" role="tabpanel" aria-labelledby="articles-tab">
				  	<?php if (!empty($posts)): ?>
						<?php foreach ($posts as $key => $post): ?>
						<div class="search-pane mt-4">
							<div class="row my-lg-3">
								<div class="col-12 d-block d-lg-none">
									<h4>
										<a href="article/<?php echo $post['slug']; ?>" target="_blank" style="text-decoration:underline;"><?php echo $post['title']; ?></a>
									</h4>
								</div>
								<div class="col-9 order-lg-last">
									<h4 class="d-none d-lg-block">
										<a href="article/<?php echo $post['slug']; ?>" target="_blank" style="text-decoration:underline;"><?php echo $post['title']; ?></a>
									</h4>
									<p><?php echo $post['content']; ?></p>
									<p class="small float-lg-right"><em>Δημοσιεύτηκε στις <?php echo date("j F Y", strtotime($post['created_at'])); ?></em></p>
								</div>
								<div class="col-3">
									<a href="article/<?php echo $post['slug']; ?>" target="_blank">
										<img src="uploads/images/articles/<?php echo $post['image']; ?>" alt="image" class="img-fluid">
									</a>
								</div>	
							</div>
							<div class="d-flex justify-content-center align-items-center borderimg">
								<picture class="ml-1">
									<source media="(max-width: 767.98px)" srcset="images/grape-border-10.png">
									<source media="(min-width: 768px)" srcset="images/grape-border.png">
									<img src="images/grape-border.png" alt="grape-image">
								</picture>
								<picture class="mx-2">
									<source media="(max-width: 767.98px)" srcset="images/grape-border-10.png">
									<source media="(min-width: 768px)" srcset="images/grape-border.png">
									<img src="images/grape-border.png" alt="grape-image">
								</picture>
								<picture class="mr-2">
									<source media="(max-width: 767.98px)" srcset="images/grape-border-10.png">
									<source media="(min-width: 768px)" srcset="images/grape-border.png">
									<img src="images/grape-border.png" alt="grape-image">
								</picture>
							</div>
						</div>
						<?php endforeach; ?>
					<?php else: ?>
						<h3 class="text-center mt-5">Δεν βρέθηκαν αποτελέσματα</h3>
					<?php endif; ?>
				</div>
				
				<div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="wine-reviews-tab">
					<?php if (!empty($wines)): ?>
				  		<?php foreach ($wines as $key => $wine): ?>
							<div class="search-pane mt-4">
								<div class="row my-lg-3">
									<div class="col-12 d-block d-lg-none">
										<h4>
											<a href="wine_review/<?php echo $wine['slug']; ?>" target="_blank" style="text-decoration:underline;"><?php echo $wine['title']; ?></a>
										</h4>
									</div>
									<div class="col-9 order-lg-last">
										<h4 class="d-none d-lg-block">
											<a href="wine_review/<?php echo $wine['slug']; ?>" target="_blank" style="text-decoration:underline;"><?php echo $wine['title']; ?></a>
										</h4>
										<p><?php echo $wine['description']; ?></p>
										<p class="small float-lg-right"><em>Δημοσιεύτηκε στις <?php echo date("j F Y", strtotime($wine['created_at'])); ?></em></p>
									</div>
									<div class="col-3">
										<a href="wine_review/<?php echo $wine['slug']; ?>" target="_blank">
											<img src="uploads/images/wines/<?php echo $wine['imageh']; ?>" alt="image" class="img-fluid">
										</a>
									</div>
								</div>
								<div class="d-flex justify-content-center align-items-center borderimg">
									<picture class="ml-1">
									  <source media="(max-width: 767.98px)" srcset="images/grape-border-10.png">
									  <source media="(min-width: 768px)" srcset="images/grape-border.png">
									  <img src="images/grape-border.png" alt="grape-image">
									</picture>
									<picture class="mx-2">
									  <source media="(max-width: 767.98px)" srcset="images/grape-border-10.png">
									  <source media="(min-width: 768px)" srcset="images/grape-border.png">
									  <img src="images/grape-border.png" alt="grape-image">
									</picture>
									<picture class="mr-2">
									  <source media="(max-width: 767.98px)" srcset="images/grape-border-10.png">
									  <source media="(min-width: 768px)" srcset="images/grape-border.png">
									  <img src="images/grape-border.png" alt="grape-image">
									</picture>
								</div>
							</div>
						<?php endforeach; ?>
					<?php else: ?>
						<h3 class="text-center mt-5">Δεν βρέθηκαν αποτελέσματα</h3>
					<?php endif; ?>
				</div>
			</div>	
		</div>
	</div>
</div> <!-- end wrapper -->